<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentMigrator.Runner.SQLite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Dapper\FclEx.Dapper.csproj" />
    <ProjectReference Include="..\FclEx.Core.Tests\FclEx.Core.Tests.csproj" />
    <ProjectReference Include="..\FclEx.DatabaseTesting\FclEx.DatabaseTesting.csproj" />
  </ItemGroup>
</Project>
