<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Core" />
    <PackageReference Include="AspectCore.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FclEx.Caching\FclEx.Caching.csproj" />
    <ProjectReference Include="..\FclEx.Http\FclEx.Http.csproj" />
    <ProjectReference Include="..\FclEx.SourceGenerator\FclEx.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <Import Project="..\EmitGeneratedFiles.props" />
  <Import Project="FclEx.Abp.targets" />
  <ItemGroup>
    <Content Include="$(GeneratedSourceDir)\FclEx.SourceGenerator\FclEx.SourceGenerator\AbpCoreUsings.cs" Link="AbpCoreUsings.cs" Pack="true" PackagePath="content\" Visible="false" />
    <Content Include="FclEx.Abp.props" Pack="true" BuildAction="None" PackagePath="buildTransitive\FclEx.Abp.props" />
    <Content Include="FclEx.Abp.targets" Pack="true" BuildAction="None" PackagePath="buildTransitive\FclEx.Abp.targets" />
  </ItemGroup>
</Project>
