<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace></RootNamespace>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="[7.0.18, 8.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\FclEx\src\FclEx.Dapper\FclEx.Dapper.csproj" />
  </ItemGroup>

</Project>