<Project>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);xUnit2013;xUnit1041;NU1901;NU1902;NU1903;NU1904;xUnit1051;AD0001</NoWarn>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFrameworkVersion>$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)', 2))</TargetFrameworkVersion>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <SuppressTfmSupportBuildErrors>true</SuppressTfmSupportBuildErrors>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <PropertyGroup>
    <!--<DefineConstants Condition="'$(TargetFramework)' == 'net10.0'">$(DefineConstants);DISABLE_NPGSQL</DefineConstants>-->
    <DefineConstants Condition="'$(TargetFramework)' == 'net10.0'">$(DefineConstants);DISABLE_MYSQL</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
    <_RootDir>$(MSBuildThisFileDirectory)..\</_RootDir>
    <VSTestLogger>trx%3bLogFileName=$(MSBuildProjectName).trx</VSTestLogger>
    <!--<VSTestResultsDirectory>$(_RootDir)TestResults$(Configuration)\$(TargetFramework)</VSTestResultsDirectory>-->
    <VSTestResultsDirectory>$([System.IO.Path]::Combine($(_RootDir), TestResults, $(Configuration), $(TargetFramework)))</VSTestResultsDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="TestData\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <__DisableParallel Include="FclEx.Core.Tests" />
    <__DisableParallel Include="FclEx.Xunit.Tests" />
    <__DisableParallel Include="FclEx.Xunit.v3.Tests" />
    <AssemblyAttribute Include="Xunit.TestFramework" 
                       Condition="$([System.String]::Copy(@(__DisableParallel)).Contains($(MSBuildProjectName))) != 'False' ">
      <_Parameter1>Meziantou.Xunit.ParallelTestFramework</_Parameter1>
      <_Parameter2>Meziantou.Xunit.ParallelTestFramework</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::VersionLessThan($(TargetFrameworkVersion), 8.0))">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="[17.13.0]" />
    <PackageReference Include="xunit.runner.visualstudio" Version="[3.0.2]" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(TargetFrameworkVersion), 8.0))">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="all" />
  </ItemGroup>

</Project>