// ReSharper disable RedundantUsingDirective
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;

namespace FclEx.Utils;

public sealed class SourceBuilder : IDisposable
{
    private readonly StringBuilder _builder = new();
    private readonly StringWriter _stringWriter;
    private readonly IndentedTextWriter _writer;

    public SourceBuilder()
    {
        _stringWriter = new StringWriter(_builder);
        _writer = new IndentedTextWriter(_stringWriter, new string(' ', 4));
    }

    public void Dispose()
    {
        _stringWriter.Dispose();
        _writer.Dispose();
    }

    public SourceBuilder WriteLine(string? value = null)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            _writer.WriteLineNoTabs(null!);
        }
        else
        {
            _writer.WriteLine(value);
        }

        return this;
    }

    public string NewLine => _writer.NewLine;

    public bool EndsWith(string value)
    {
        if (_builder.Length < value.Length)
            return false;

        var sbLength = _builder.Length;
        var textLength = value.Length;
        for (var i = 1; i <= textLength; i++)
        {
            if (value[textLength - i] != _builder[sbLength - i])
                return false;
        }
        return true;
    }

    /// <summary>
    /// Only keep one line terminator if this ends with multiple ones.
    /// </summary>
    /// <returns></returns>
    public SourceBuilder RemoveExtraNewLines()
    {
        var newLines = NewLine + NewLine;
        while (EndsWith(newLines))
        {
            _builder.Length -= NewLine.Length;
        }
        return this;
    }

    public SourceBuilder Write(string? value = null)
    {
        _writer.Write(value);
        return this;
    }

    public SourceBuilder WriteLineNoTabs(string? value)
    {
        _writer.WriteLineNoTabs(value!);
        return this;
    }

    public SourceBuilder Indent()
    {
        _writer.Indent++;
        return this;
    }

    public SourceBuilder Unindent()
    {
        _writer.Indent--;
        return this;
    }

    public override string ToString() => _stringWriter.ToString();
}

public static class SourceBuilderExtensions
{
    public static SourceBuilder WriteOpeningBracket(this SourceBuilder builder)
    {
        builder.WriteLine("{");
        builder.Indent();
        return builder;
    }

    public static SourceBuilder WriteClosingBracket(this SourceBuilder builder)
    {
        builder.RemoveExtraNewLines();
        builder.Unindent();
        builder.WriteLine("}");
        return builder;
    }

    public static SourceBuilder WriteSummary(this SourceBuilder builder, IEnumerable<string> lines)
    {
        builder.WriteLine("/// <summary>");
        foreach (var line in lines)
        {
            var tagText = SecurityElement.Escape(line)!.Trim();
            builder.Write("/// ");
            builder.Write(tagText);
            builder.WriteLine(" <br/>");
        }
        builder.WriteLine("/// </summary>");

        return builder;
    }

    public static SourceBuilder WriteUsing(this SourceBuilder builder, string @using)
    {
        return builder.WriteLine($"using {@using};");
    }

    public static SourceBuilder WriteUsings(this SourceBuilder builder, IEnumerable<string> usings)
    {
        foreach (var u in usings.OrderBy(s => s))
        {
            builder.WriteUsing(u);
        }
        return builder;
    }

    public static SourceBuilder WriteGeneratedHeader(this SourceBuilder builder)
    {
        return builder.WriteLine("// <auto-generated />");
    }

    public static SourceBuilder WriteEnableNullable(this SourceBuilder builder)
    {
        return builder.WriteLine("#nullable enable");
    }

    public static SourceBuilder WriteNamespace(this SourceBuilder builder, string @namespace)
    {
        return builder.WriteLine($"namespace {@namespace}");
    }

    /// <summary>
    /// Writes a conditional compilation directive for the specified symbol.
    /// </summary>
    /// <param name="builder">The SourceBuilder instance to which the directive is added.</param>
    /// <param name="symbol">The symbol to be checked in the conditional compilation.</param>
    /// <returns>The updated SourceBuilder instance.</returns>
    public static SourceBuilder WriteIf(this SourceBuilder builder, string symbol)
    {
        return builder.WriteLineNoTabs($"#if {symbol}");
    }

    /// <summary>
    /// Writes an 'else if' conditional compilation directive for the specified symbol.
    /// </summary>
    /// <param name="builder">The SourceBuilder instance to which the directive is added.</param>
    /// <param name="symbol">The symbol to be checked in the 'else if' conditional compilation.</param>
    /// <returns>The updated SourceBuilder instance.</returns>
    public static SourceBuilder WriteElif(this SourceBuilder builder, string symbol)
    {
        return builder.WriteLineNoTabs($"#elif {symbol}");
    }

    /// <summary>
    /// Writes an 'else' conditional compilation directive.
    /// </summary>
    /// <param name="builder">The SourceBuilder instance to which the directive is added.</param>
    /// <returns>The updated SourceBuilder instance.</returns>
    public static SourceBuilder WriteElse(this SourceBuilder builder)
    {
        return builder.WriteLineNoTabs("#else");
    }

    /// <summary>
    /// Writes the end of a conditional compilation directive.
    /// </summary>
    /// <param name="builder">The SourceBuilder instance to which the directive is added.</param>
    /// <returns>The updated SourceBuilder instance.</returns>
    public static SourceBuilder WriteEndIf(this SourceBuilder builder)
    {
        return builder.WriteLineNoTabs("#endif");
    }

    /// <summary>
    /// Writes a directive to define a symbol for conditional compilation.
    /// </summary>
    /// <param name="builder">The SourceBuilder instance to which the directive is added.</param>
    /// <param name="symbol">The symbol to be defined.</param>
    /// <returns>The updated SourceBuilder instance.</returns>
    public static SourceBuilder WriteDefine(this SourceBuilder builder, string symbol)
    {
        return builder.WriteLineNoTabs($"#define {symbol}");
    }

    public static SourceBuilder WriteAsLines(this SourceBuilder builder, string text)
    {
        var lines = text.Split(["\r\n"], StringSplitOptions.None);
        foreach (var line in lines)
        {
            builder.WriteLine(line);
        }
        return builder;
    }
}