<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="EasyCaching.CSRedis" Version="1.9.2" />
    <PackageReference Include="EasyCaching.Serialization.MessagePack" Version="1.9.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx.Abp\FclEx.Abp.csproj" />
  </ItemGroup>

</Project>
