<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.1" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.11" />
    <PackageReference Include="Xunit.Extensions.AssemblyFixture" Version="2.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\FclEx\src\FclEx.Dapper\FclEx.Dapper.csproj" />
    <ProjectReference Include="..\..\src\FclEx.Abp.EfCore\FclEx.Abp.EfCore.csproj" />
    <ProjectReference Include="..\..\src\FclEx.Abp.Xunit\FclEx.Abp.Xunit.csproj" />
  </ItemGroup>

</Project>