<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <RootNamespace></RootNamespace>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="InterfaceBaseInvoke.Fody" Version="0.1.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Dapper\FclEx.Dapper.csproj" />
    <ProjectReference Include="..\..\src\FclEx.Http\FclEx.Http.csproj" />
    <ProjectReference Include="..\..\src\FclEx.Core\FclEx.Core.csproj" />
  </ItemGroup>

</Project>
