<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="NewRelic.Agent.Api" Version="10.20.2" />
    <PackageReference Include="GraphQL.Client" Version="6.0.2" />
    <PackageReference Include="GraphQL.Client.Serializer.Newtonsoft" Version="6.0.5" />
    <PackageReference Include="System.Linq.Async.Queryable" Version="6.0.1" />
    <PackageReference Include="SlackNet.AspNetCore" Version="0.12.2" />
    <PackageReference Include="Atlassian.SDK" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx.AspNetCore\FclEx.AspNetCore.csproj" />
  </ItemGroup>

</Project>
