<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="NewRelic.Agent.Api" Version="10.33.1" />
    <PackageReference Include="GraphQL.Client" Version="6.1.0" />
    <PackageReference Include="GraphQL.Client.Serializer.Newtonsoft" Version="6.1.0" />
    <PackageReference Include="System.Linq.Async.Queryable" Version="6.0.1" />
    <PackageReference Include="SlackNet.AspNetCore" Version="0.15.2" />
    <PackageReference Include="Atlassian.SDK" Version="13.0.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx.Http\FclEx.Http.csproj" />
  </ItemGroup>

</Project>
