namespace FclEx.Extensions;

partial class StringBuilderExtensions
{
    /// <summary>
    /// Appends content generated by <paramref name="content"/> wrapped between the specified
    /// opening and closing characters.
    /// </summary>
    /// <param name="builder">The target <see cref="StringBuilder"/>.</param>
    /// <param name="open">The characters to append before the generated content.</param>
    /// <param name="content">An action that writes the inner content to the builder.</param>
    /// <param name="close">
    /// The characters to append after the generated content. If <see langword="null"/>, <paramref name="open"/> is used.
    /// </param>
    /// <returns>The same <see cref="StringBuilder"/> instance for chaining.</returns>
    /// <remarks>
    /// Example:
    /// <code>
    /// builder.AppendWrapped('{', b => b.Append("x: ").Append(10), '}');
    /// // Result: {x: 10}
    /// </code>
    /// </remarks>
    public static StringBuilder AppendWrapped(this StringBuilder builder, string open, Action<StringBuilder> content, string? close = null)
    {
        Check.NotNull(builder);
        Check.NotEmpty(open);
        Check.NotNull(content);

        close ??= open;
        builder.Append(open);
        builder.Append(content);
        builder.Append(close);
        return builder;
    }

    /// <summary>
    /// Appends content generated by <paramref name="content"/> wrapped between the specified
    /// opening and closing characters.
    /// </summary>
    /// <param name="builder">The target <see cref="StringBuilder"/>.</param>
    /// <param name="open">The character to append before the generated content.</param>
    /// <param name="content">An action that writes the inner content to the builder.</param>
    /// <param name="close">
    /// The character to append after the generated content. If <see langword="null"/>, <paramref name="open"/> is used.
    /// </param>
    /// <returns>The same <see cref="StringBuilder"/> instance for chaining.</returns>
    /// <remarks>
    /// Example:
    /// <code>
    /// builder.AppendWrapped('{', b => b.Append("x: ").Append(10), '}');
    /// // Result: {x: 10}
    /// </code>
    /// </remarks>
    public static StringBuilder AppendWrapped(this StringBuilder builder, char open, Action<StringBuilder> content, char? close = null)
    {
        return builder.AppendWrapped(open.ToString(), content, close?.ToString());
    }

    /// <summary>
    /// Appends <paramref name="value"/> wrapped between the specified opening and closing characters.
    /// </summary>
    /// <param name="builder">The target <see cref="StringBuilder"/>.</param>
    /// <param name="open">The characters to append before the value.</param>
    /// <param name="value">
    /// The value to append inside the delimiters. If <see langword="null"/>, nothing is appended between
    /// the opening and closing characters.
    /// </param>
    /// <param name="close">
    /// The characters to append after the value. If <see langword="null"/>, <paramref name="open"/> is used.
    /// </param>
    /// <returns>The same <see cref="StringBuilder"/> instance for chaining.</returns>
    /// <remarks>
    /// Example:
    /// <code>
    /// builder.AppendWrapped('(', 42, ')');
    /// // Result: (42)
    ///
    /// builder.AppendWrapped('"', "text");
    /// // Result: "text"
    /// </code>
    /// </remarks>
    public static StringBuilder AppendWrapped(this StringBuilder builder, string open, object? value, string? close = null)
    {
        Check.NotNull(builder);
        Check.NotEmpty(open);

        close ??= open;
        builder.Append(open);
        builder.Append(value);
        builder.Append(close);
        return builder;
    }

    /// <summary>
    /// Appends <paramref name="value"/> wrapped between the specified opening and closing characters.
    /// </summary>
    /// <param name="builder">The target <see cref="StringBuilder"/>.</param>
    /// <param name="open">The character to append before the value.</param>
    /// <param name="value">
    /// The value to append inside the delimiters. If <see langword="null"/>, nothing is appended between
    /// the opening and closing characters.
    /// </param>
    /// <param name="close">
    /// The character to append after the value. If <see langword="null"/>, <paramref name="open"/> is used.
    /// </param>
    /// <returns>The same <see cref="StringBuilder"/> instance for chaining.</returns>
    /// <remarks>
    /// Example:
    /// <code>
    /// builder.AppendWrapped('(', 42, ')');
    /// // Result: (42)
    ///
    /// builder.AppendWrapped('"', "text");
    /// // Result: "text"
    /// </code>
    /// </remarks>
    public static StringBuilder AppendWrapped(this StringBuilder builder, char open, object? value, char? close = null)
    {
        return builder.AppendWrapped(open.ToString(), value, close?.ToString());
    }
}
