<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::VersionLessThan($(TargetFrameworkVersion), 8.0))">
    <!--net6.0 and net7.0 require this package to support CollectionBuilder-->
    <PackageReference Include="PolySharp" Version="1.15.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx.Core\FclEx.Core.csproj" />
  </ItemGroup>

</Project>
