<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\nupkg\common.test.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Http\FclEx.Http.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\SimpleCookies.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
  </ItemGroup>

</Project>
