// <auto-generated />

using System;
using System.Reflection;

namespace FclEx.Helpers
{
    partial class MethodHelper
    {
        public static MethodInfo GetMethod<T1>(Action<T1> action) => action.Method;
        public static MethodInfo GetMethod<T1, TResult>(Func<T1, TResult> func) => func.Method;
        public static MethodInfo GetMethod<T1, T2>(Action<T1, T2> action) => action.Method;
        public static MethodInfo GetMethod<T1, T2, TResult>(Func<T1, T2, TResult> func) => func.Method;
        public static MethodInfo GetMethod<T1, T2, T3>(Action<T1, T2, T3> action) => action.Method;
        public static MethodInfo GetMethod<T1, T2, T3, TResult>(Func<T1, T2, T3, TResult> func) => func.Method;
        public static MethodInfo GetMethod<T1, T2, T3, T4>(Action<T1, T2, T3, T4> action) => action.Method;
        public static MethodInfo GetMethod<T1, T2, T3, T4, TResult>(Func<T1, T2, T3, T4, TResult> func) => func.Method;
        public static MethodInfo GetMethod<T1, T2, T3, T4, T5>(Action<T1, T2, T3, T4, T5> action) => action.Method;
        public static MethodInfo GetMethod<T1, T2, T3, T4, T5, TResult>(Func<T1, T2, T3, T4, T5, TResult> func) => func.Method;
        public static MethodInfo GetMethod<T1, T2, T3, T4, T5, T6>(Action<T1, T2, T3, T4, T5, T6> action) => action.Method;
        public static MethodInfo GetMethod<T1, T2, T3, T4, T5, T6, TResult>(Func<T1, T2, T3, T4, T5, T6, TResult> func) => func.Method;
        public static MethodInfo GetMethod<T1, T2, T3, T4, T5, T6, T7>(Action<T1, T2, T3, T4, T5, T6, T7> action) => action.Method;
        public static MethodInfo GetMethod<T1, T2, T3, T4, T5, T6, T7, TResult>(Func<T1, T2, T3, T4, T5, T6, T7, TResult> func) => func.Method;
        public static MethodInfo GetMethod<T1, T2, T3, T4, T5, T6, T7, T8>(Action<T1, T2, T3, T4, T5, T6, T7, T8> action) => action.Method;
        public static MethodInfo GetMethod<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> func) => func.Method;
    }
}
