// <auto-generated />

using System;
using System.Reflection;

namespace FclEx.Extensions
{
    partial class TypeExtensions
    {
        public static Type MakeGenericType<T1>(this Type type)
        {
            return type.MakeGenericType(typeof(T1));
        }
        public static Type MakeGenericType<T1, T2>(this Type type)
        {
            return type.MakeGenericType(typeof(T1), typeof(T2));
        }
        public static Type MakeGenericType<T1, T2, T3>(this Type type)
        {
            return type.MakeGenericType(typeof(T1), typeof(T2), typeof(T3));
        }
        public static Type MakeGenericType<T1, T2, T3, T4>(this Type type)
        {
            return type.MakeGenericType(typeof(T1), typeof(T2), typeof(T3), typeof(T4));
        }
        public static Type MakeGenericType<T1, T2, T3, T4, T5>(this Type type)
        {
            return type.MakeGenericType(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5));
        }
        public static Type MakeGenericType<T1, T2, T3, T4, T5, T6>(this Type type)
        {
            return type.MakeGenericType(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6));
        }
        public static Type MakeGenericType<T1, T2, T3, T4, T5, T6, T7>(this Type type)
        {
            return type.MakeGenericType(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7));
        }
        public static Type MakeGenericType<T1, T2, T3, T4, T5, T6, T7, T8>(this Type type)
        {
            return type.MakeGenericType(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7), typeof(T8));
        }
    }
}
