using System.Linq;

namespace FclEx.SourceGenerator.Sources
{
    internal static class MethodHelperSource
    {
        private const int Max = 8;
        private const string RootNamespace = "FclEx.Helpers";
        private const string GeneratedFilesHeader = "// <auto-generated />";
        private static readonly string[] _usings =
        {
            "System",
            "System.Reflection",
        };

        internal static (string FileName, string Code) Generate()
        {
            const string className = "MethodHelper";
            const string methodName = "public static MethodInfo GetMethod";

            using var builder = new SourceBuilder()
                .WriteLine(GeneratedFilesHeader)
                .WriteLine()
                .WriteUsings(_usings)
                .WriteLine();

            // Namespace declaration
            builder.WriteLine($"namespace {RootNamespace}")
                .WriteOpeningBracket();

            // Class declaration
            builder.WriteLine($"partial class {className}")
                .WriteOpeningBracket();

            for (var i = 1; i <= Max; i++)
            {
                var types = Enumerable.Range(1, i).Select(m => "T" + m).JoinWith(", ");
                builder.WriteLine($"{methodName}<{types}>(Action<{types}> action) => action.Method;");
                builder.WriteLine($"{methodName}<{types}, TResult>(Func<{types}, TResult> func) => func.Method;");
            }

            // End class declaration
            builder.WriteClosingBracket();

            // End namespace declaration
            builder.WriteClosingBracket();

            var str = builder.ToString();
            return ($"{className}.g.cs", str);
        }

    }
}
