<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AspectCore.Extensions.LightInject" Version="2.4.0" />
    <!--<PackageReference Include="AspectCore.Core" Version="2.2.0" />-->
    <PackageReference Include="LightInject" Version="6.6.4" />
    <PackageReference Include="EasyCaching.InMemory" Version="1.9.2" />
    <PackageReference Include="EasyCaching.Serialization.Json" Version="1.9.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="Volo.Abp.AutoMapper" Version="[8.1.4]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\FclEx\src\FclEx.Http\FclEx.Http.csproj" />
    <ProjectReference Include="..\..\..\FclEx\src\FclEx.Serilog\FclEx.Serilog.csproj" />
  </ItemGroup>
</Project>
