namespace FclEx.SourceGenerator.Sources;

internal class ValueTupleExtensionsSource
{
    private const int Max = 8;
    private const string RootNamespace = "FclEx.Extensions";
    private const string GeneratedFilesHeader = "// <auto-generated />";
    private static readonly string[] _usings =
    {
        "System",
        "System.Reflection",
    };

    internal static (string FileName, string Code) Generate()
    {
        const string className = "ValueTupleExtensions";
        const string methodName = "public static string? FirstNotEmpty";

        using var builder = new SourceBuilder()
            .WriteLine(GeneratedFilesHeader)
            .WriteLine()
            .WriteLine("#nullable enable")
            .WriteUsings(_usings)
            .WriteLine();

        // Namespace declaration
        builder.WriteLine($"namespace {RootNamespace}")
            .WriteOpeningBracket();

        // Class declaration
        builder.WriteLine($"partial class {className}")
            .WriteOpeningBracket();

        for (var i = 2; i <= Max; i++)
        {
            builder.WriteLine("[return: NotNullIfNotNull(nameof(defaultValue))]");
            var types = Enumerable.Repeat("string?", i).JoinWith(", ");
            builder.WriteLine($"{methodName}(this ({types}) tuple, string? defaultValue = \"\")");
            builder.WriteOpeningBracket();
            builder.WriteLine($"using var disposable = ArrayPool<string?>.Shared.GetAsDisposable({i});");
            builder.WriteLine("var arr = disposable.Value;");
            for (var j = 0; j < i; j++)
            {
                builder.WriteLine($"arr[{j}] = tuple.Item{j + 1};");
            }
            builder.WriteLine($"return arr.FirstNotEmpty({i}, defaultValue);");
            builder.WriteClosingBracket();
            builder.WriteLine();
        }

        // End class declaration
        builder.WriteClosingBracket();

        // End namespace declaration
        builder.WriteClosingBracket();

        var str = builder.ToString();
        return ($"{className}.g.cs", str);
    }
}
