<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Dapper\FclEx.Dapper.csproj" />
    <ProjectReference Include="..\..\src\FclEx.EfCore\FclEx.EfCore.csproj" />
  </ItemGroup>
  
</Project>
