<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0' OR '$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="[7.0.11, 8.0.0)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="[8.0.0, 9.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Dapper\FclEx.Dapper.csproj" />
    <ProjectReference Include="..\..\src\FclEx.EfCore\FclEx.EfCore.csproj" />
    <ProjectReference Include="..\FclEx.Test\FclEx.Test.csproj" />
  </ItemGroup>
  
</Project>
