<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <DefineConstants>$(DefineConstants);FCLEX_XUNIT_V3</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Xunit.v3.ParallelTestFramework" Version="1.0.6" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Xunit.v3\FclEx.Xunit.v3.csproj" />
    <ProjectReference Include="..\..\src\FclEx.Xunit.v3.SourceGenerator\FclEx.Xunit.v3.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\FclEx.Xunit.Tests\**\*.cs" Exclude="..\FclEx.Xunit.Tests\obj\**\*;..\FclEx.Xunit.Tests\bin\**\*" />
  </ItemGroup>

  <Import Project="..\..\src\EmitGeneratedFiles.props" Condition=" '$(Configuration)' == 'Debug' AND $(GITHUB_ACTION) == '' AND '$(OS)' == 'Windows_NT' " />

</Project>
