<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Meziantou.Xunit.v3.ParallelTestFramework" Version="1.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Xunit.v3\FclEx.Xunit.v3.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\FclEx.Xunit.Tests\**\*.cs"
             Exclude="..\FclEx.Xunit.Tests\obj\**\*;..\FclEx.Xunit.Tests\bin\**\*" />
  </ItemGroup>

</Project>
