<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="AngleSharp" />
    <!--fix package version conflict brought by AngleSharp-->
    <PackageReference Include="System.Text.Encoding.CodePages" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="StandardSocketsHttpHandler" />
    <PackageReference Include="PolySharp" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FclEx.Logging\FclEx.Logging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)..\FclEx.Core\FclExUsing.cs" />
  </ItemGroup>
</Project>