<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\nupkg\common.props" />

  <ItemGroup>
    <PackageReference Include="MimeTypeMap.Core" Version="1.0.0" />
    <PackageReference Include="HttpMultipartParser" Version="4.4.0" />
    <PackageReference Include="AngleSharp" Version="0.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx\FclEx.csproj" />
  </ItemGroup>
  
</Project>
