<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.8" />
    <PackageReference Include="AngleSharp" Version="1.3.0" />
    <!--fix package version conflict brought by AngleSharp-->
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="StandardSocketsHttpHandler" Version="2.2.0.8" />
    <PackageReference Include="PolySharp" Version="1.15.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx.Logging\FclEx.Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)..\FclEx.Core\FclExUsing.cs" />
  </ItemGroup>

</Project>
