<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <IsTestProject>false</IsTestProject>
    <DefineConstants>$(DefineConstants);FCLEX_XUNIT_V3</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" Version="3.2.2" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::VersionLessThan($(TargetFrameworkVersion), 8.0))">
    <!--net6.0 and net7.0 require this package to support CollectionBuilder-->
    <PackageReference Include="PolySharp" Version="1.15.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx.Logging\FclEx.Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx.SourceGenerator\FclEx.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Import Project="..\EmitGeneratedFiles.props" Condition=" '$(Configuration)' == 'Debug' AND $(GITHUB_ACTION) == '' AND '$(OS)' == 'Windows_NT' " />

  <ItemGroup>
    <Compile Include="..\FclEx.Xunit\**\*.cs"
             Exclude="..\FclEx.Xunit\obj\**\*;..\FclEx.Xunit\bin\**\*" />
  </ItemGroup>

</Project>
