// <auto-generated />
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace System.Collections;

public static class SR
{
    public static string Format([StringSyntax("CompositeFormat")] string format, params object?[] args)
    {
        return string.Format(format, args);
    }
    
    public const string Arg_ArrayPlusOffTooSmall = "Destination array is not long enough to copy all the items in the collection. Check array index and length.";
    public const string Arg_HTCapacityOverflow = "Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.";
    public const string Arg_KeyNotFound = "The given key was not present in the dictionary.";
    public const string Arg_KeyNotFoundWithKey = "The given key '{0}' was not present in the dictionary.";
    public const string Arg_NonZeroLowerBound = "The lower bound of target array must be zero.";
    public const string Arg_RankMultiDimNotSupported = "Only single dimensional arrays are supported for the requested action.";
    public const string Arg_WrongType = "The value '{0}' is not of type '{1}' and cannot be used in this generic collection.";
    public const string Argument_AddingDuplicate = "An item with the same key has already been added. Key: {0}";
    public const string Argument_IncompatibleArrayType = "Target array type is not compatible with the type of items in the collection.";
    public const string ArgumentOutOfRange_Generic_MustBeGreater = "{0} ('{1}') must be greater than '{2}'.";
    public const string ArgumentOutOfRange_Generic_MustBeGreaterOrEqual = "{0} ('{1}') must be greater than or equal to '{2}'.";
    public const string ArgumentOutOfRange_Generic_MustBeLess = "{0} ('{1}') must be less than '{2}'.";
    public const string ArgumentOutOfRange_Generic_MustBeLessOrEqual = "{0} ('{1}') must be less than or equal to '{2}'.";
    public const string ArgumentOutOfRange_Generic_MustBeNonNegative = "{0} ('{1}') must be a non-negative value.";
    public const string InvalidOperation_ConcurrentOperationsNotSupported = "Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.";
    public const string InvalidOperation_EnumEnded = "Enumeration already finished.";
    public const string InvalidOperation_EnumFailedVersion = "Collection was modified after the enumerator was instantiated.";
    public const string InvalidOperation_EnumNotStarted = "Enumeration has not started. Call MoveNext.";
    public const string Arg_CannotBeNaN = "TimeSpan does not accept floating point Not-a-Number values.";
    public const string Overflow_TimeSpanTooLong = "TimeSpan overflowed because the duration is too long.";
}
