<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    <DefineConstants>$(DefineConstants);FCLEX_INTERNAL</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AngleSharp" PrivateAssets="all" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference Include="PolySharp" PrivateAssets="all" />
  </ItemGroup>
  <Target Name="GetDependencyTargetPaths">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="$(PkgAngleSharp)\lib\netstandard2.0\AngleSharp.dll" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>
  <ItemGroup>
    <Compile Include="..\FclEx.Core\FclEx\Utils\SourceBuilder.cs" />
  </ItemGroup>
</Project>