<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    <DefineConstants>$(DefineConstants);FCLEX_INTERNAL</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.3.0" PrivateAssets="all" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0" PrivateAssets="all" />
    <!--NOTE: cannot use the latest version of Microsoft.CodeAnalysis.CSharp because it will cause the warning CS9057-->
    <!--the warning will cause the source generator not to generate the source code-->
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="[4.14.0]" PrivateAssets="all" />
    <PackageReference Include="PolySharp" Version="1.15.0" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="GetDependencyTargetPaths">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="$(PkgAngleSharp)\lib\netstandard2.0\AngleSharp.dll" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <Compile Include="..\FclEx.Core\FclEx\Utils\SourceBuilder.cs" />
  </ItemGroup>

</Project>