<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>YamlDotNet helpers, options, converters, naming conventions, and YAML node extensions.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FclEx.Core\FclEx.Core.csproj" />
  </ItemGroup>
</Project>
