<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Cooperation\FclEx.Cooperation.csproj" />
    <ProjectReference Include="..\FclEx.Tests\FclEx.Tests.csproj" />
  </ItemGroup>

</Project>
