<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="PolySharp" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FclEx.Logging\FclEx.Logging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)..\FclEx.Core\FclExUsings.cs" />
  </ItemGroup>
</Project>