<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\FclEx\src\FclEx.EfCore\FclEx.EfCore.csproj" />
    <ProjectReference Include="..\..\..\FclEx\src\FclEx.Core\FclEx.Core.csproj" />
    <ProjectReference Include="..\FclEx.Abp\FclEx.Abp.csproj" />
  </ItemGroup>
</Project>
