<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ServiceStack.OrmLite</RootNamespace>
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
    <DefineConstants>$(DefineConstants);NETCORE;DISABLE_FCLEX_USING</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ServiceStack.Common" Version="6.5.0" />
    <PackageReference Include="System.Dynamic.Runtime" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
    <PackageReference Include="System.Collections.NonGeneric" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
    <PackageReference Include="System.ComponentModel.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\FclEx\src\FclEx\FclEx.csproj" />
  </ItemGroup>
</Project>
