<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\nupkg\common.test.props" />
  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="System.Management" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FclEx.Wmi">
      <HintPath>..\..\src\FclEx.Wmi\bin\$(Configuration)\net5.0-windows\FclEx.Wmi.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
