<Project>
  <Import Project="version.props" />
  <PropertyGroup>
    <RootNamespace></RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>CS8600;CS8602;CS8603;CS8625;CS8618;CS8601;CS8610;CS8604;CS8613;CS8609;CS8614;CS8620;CS8634;CS8767;CS8621;CS8607;CS8714</WarningsAsErrors>
    <LangVersion>preview</LangVersion>
    <TargetFramework>net5.0</TargetFramework>
    <PackageProjectUrl>https://github.com/huoshan12345/FclEx</PackageProjectUrl>
    <PackageTags>extensions;helpers</PackageTags>
    <Authors>huoshan12345</Authors>
    <Description>Some basic useful extensions and helpers for C# fundamental class libraries</Description>
    <RepositoryUrl>https://github.com/huoshan12345/FclEx</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>huoshan12345</Copyright>
  </PropertyGroup>

</Project>