<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="[17.13.0]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Messaging\FclEx.Messaging.csproj" />
    <ProjectReference Include="..\FclEx.Core.Tests\FclEx.Core.Tests.csproj" />
  </ItemGroup>

</Project>
