- hosts: localhost
  environment:
    ANSIBLE_HASH_BEHAVIOUR: merge
  vars:
    test_config_paths:
      - ../../src/FclEx/test/FclEx.Tests
    extra:
      Phase: "{{ phase }}"
    env: "{{ Settings.Common | combine(Settings.Envs[phase], recursive=true) | combine(extra, recursive=True) }}"
  tasks:
    - include_tasks: render_config_task.yml
      loop: "{{ test_config_paths }}"
      loop_control:
        loop_var: config_path
