<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\nupkg\common.props" />
  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="6.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.1.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="powershell.exe -Command &quot;get-wmiobject win32_process -Filter 'name = \&quot;dotnet.exe\&quot;' | where commandline -like '*$(ProjectName)*'  |  remove-wmiobject&quot;" />
  </Target>
</Project>
