<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\nupkg\common.props" />
  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.2" />
  </ItemGroup>

</Project>
