<Project>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
    <NoWarn>xUnit2013;xUnit1000;CS1591;CS2002;CS8500</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <_RootDir>$(MSBuildThisFileDirectory)../../</_RootDir>
    <VSTestLogger>trx%3bLogFileName=$(MSBuildProjectName).trx</VSTestLogger>
    <VSTestResultsDirectory>$(_RootDir)TestResults/$(Configuration)/$(TargetFramework)</VSTestResultsDirectory>
    <_SettingFile>appsettings.json</_SettingFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(_SettingFile)" Condition="Exists('$(_SettingFile)')">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="test-data\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>