<Project>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net6.0</TargetFramework>
    <NoWarn>xUnit2013</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="FclEx.Utils" />
    <Using Include="FclEx.Extensions" />
  </ItemGroup>

</Project>