<Project>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
    <NoWarn>xUnit2013</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>