// Global using directives

global using System.Collections.Concurrent;
global using System.Data;
global using System.Data.Common;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Text;
global using Dapper;
global using FclEx.Dapper;
global using FclEx.Databases;
global using FclEx.Domain;
global using FclEx.EfCore;
global using FclEx.Extensions;
global using FclEx.Tests;
global using FclEx.Xunit;
global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Metadata.Conventions;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using Renci.SshNet;
global using Xunit;
global using Xunit.Sdk;
global using static FclEx.Databases.DatabaseTestSettings;
global using static FclEx.EfCore.EfCoreFixture;
global using static GlobalConstants;