<Project>
  <Target Name="CopyFclExUsing" BeforeTargets="BeforeBuild" Condition="$(DisableFclExUsing) != 'true'">
    <ItemGroup>
      <Compile Include="$(MSBuildProjectDirectory)\content\Using.cs">
        <Link>FclExUsing.cs</Link>
        <Visible>True</Visible>
      </Compile>
    </ItemGroup>
  </Target>
</Project>