namespace FclEx.Databases;

/// <summary>Creates minimal isolated tables on demand; only Oracle cascade tables persist between runs.</summary>
public sealed class TruncateTestTables(TestDatabaseEnvironment environment)
{
    private readonly Dictionary<string, SemaphoreSlim> _oracleCascadeLocks = new();

    /// <summary>Idempotently creates the two Oracle cascade tables for each selected Oracle target.</summary>
    public async Task InitializeAsync(IEnumerable<string?> schemas, CancellationToken cancellationToken = default)
    {
        if (!SelectedDrivers.Contains(DbDriver.Oracle))
            return;

        foreach (var (_, schema) in GetDriverSchemaCases(schemas).Where(pair => pair.Driver == DbDriver.Oracle))
        {
            using var connection = environment.Resolve(DbDriver.Oracle, schema).CreateConnection();
            await connection.OpenAsync(cancellationToken);
            using var session = new TruncateTestSession(connection, DbDriver.Oracle, schema, "TruncateCascade_");
            await CreateTableAsync(session, typeof(TruncateParent), false, true, cancellationToken);
            await CreateTableAsync(session, typeof(TruncateChild), false, true, cancellationToken);
            if (!_oracleCascadeLocks.ContainsKey(schema ?? ""))
                _oracleCascadeLocks.Add(schema ?? "", new SemaphoreSlim(1, 1));
        }
    }

    /// <summary>Creates only the requested tables. Ordinary tables are dropped when the session is disposed.</summary>
    /// <remarks>Oracle cascade sessions exclusively lease the persistent parent and child tables.</remarks>
    public async Task<TruncateTestSession> CreateSessionAsync(
        DbDriver driver,
        string? schema,
        IEnumerable<Type> entityTypes,
        DbConnection? connection = null,
        CancellationToken cancellationToken = default,
        bool ordinary = false)
    {
        var types = entityTypes.Distinct().ToArray();
        var oracleCascade = driver == DbDriver.Oracle && types.Contains(typeof(TruncateParent));
        Action? release = null;
        if (oracleCascade)
        {
            var gate = _oracleCascadeLocks[schema ?? ""];
            await gate.WaitAsync(cancellationToken);
            release = () => gate.Release();
        }

        var temporary = !ordinary && driver != DbDriver.Oracle;
        var prefix = oracleCascade ? "TruncateCascade_" : (temporary && driver == DbDriver.SqlServer ? "#" : "")
            + "Truncate_" + Guid.NewGuid().ToString("N").Substring(0, 12) + "_";
        var session = new TruncateTestSession(connection ?? environment.Resolve(driver, schema).CreateConnection(), driver,
            temporary ? driver switch { DbDriver.Npgsql => "pg_temp", DbDriver.SqlServer => null, _ => schema } : schema,
            prefix, release);
        try
        {
            await session.Connection.OpenAsync(cancellationToken);
            if (!oracleCascade)
            {
                foreach (var type in types)
                {
                    await CreateTableAsync(session, type, temporary, false, cancellationToken);
                    if (!temporary)
                        session.TablesToDrop.Add(session.GetQualifiedTableName(type));
                }
            }
            return session;
        }
        catch
        {
            session.Dispose();
            throw;
        }
    }

    private static Task CreateTableAsync(
        TruncateTestSession session, Type entityType, bool temporary, bool ifNotExists, CancellationToken cancellationToken)
    {
        var driver = session.Driver;
        var adapter = DapperHelper.GetSqlAdapter(session.Connection);
        var integer = driver == DbDriver.Oracle ? "NUMBER(10)" : "INTEGER";
        var columns = new List<string>();
        if (entityType != typeof(TruncateKeylessRow))
        {
            var id = entityType == typeof(TruncateManualRow) ? integer + " PRIMARY KEY" : driver switch
            {
                DbDriver.SqlServer => "INTEGER IDENTITY(1,1) PRIMARY KEY",
                DbDriver.MySql or DbDriver.MySqlConnector => "INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY",
                DbDriver.Sqlite => "INTEGER PRIMARY KEY AUTOINCREMENT",
                _ => integer + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            };
            columns.Add($"{Column("Id")} {id}");
        }
        if (entityType == typeof(TruncateRow) || entityType == typeof(TruncateOtherRow) || entityType == typeof(TruncateKeylessRow))
            columns.Add($"{Column("Value")} {integer} NOT NULL");
        if (entityType == typeof(TruncateChild))
        {
            columns.Add($"{Column("ParentId")} {integer} NOT NULL");
            columns.Add($"FOREIGN KEY ({Column("ParentId")}) REFERENCES {session.GetQualifiedTableName(typeof(TruncateParent))} ({Column("Id")}) ON DELETE CASCADE");
        }
        var create = temporary && driver != DbDriver.SqlServer ? "CREATE TEMPORARY TABLE" : "CREATE TABLE";
        var sql = $"{create} {session.GetQualifiedTableName(entityType)} ({string.Join(", ", columns)})";
        if (ifNotExists)
            sql = $"BEGIN EXECUTE IMMEDIATE '{sql.Replace("'", "''")}'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;";
        return session.Connection.ExecuteAsync(sql, cancellationToken: cancellationToken);

        string Column(string name) => adapter.GetQuotedColumnName(name);
    }
}
