<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Destructurama.Attributed" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Reference Include="System.IO.Compression" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FclEx.Http\FclEx.Http.csproj" />
  </ItemGroup>
</Project>