using System;
using System.Collections.Generic;
using System.Linq;
using System.Management;
using System.Text;
using System.Text.RegularExpressions;
using FclEx.Wmi.SourceGenerator.Extensions;
using FclEx.Wmi.SourceGenerator.Models;

namespace FclEx.Wmi.SourceGenerator.Sources
{
    public static class ClassItemSource
    {
        internal const string GeneratedFilesHeader = "// <auto-generated />";

        private static readonly Regex _regex = new(@"(?<=[^_])_+(?=[^_])", RegexOptions.Compiled);

        internal static (string FileName, string Code) Generate(string @namespace, ClassItem classItem)
        {
            var usings = new List<string> { "System" };

            using var builder = new SourceBuilder()
                                .WriteLine(GeneratedFilesHeader)
                                .WriteLine()
                                .WriteUsings(usings)
                                .WriteLine();

            var ns = @namespace.TrimStart("root\\", StringComparison.OrdinalIgnoreCase).Replace("\\", ".");

            // Namespace declaration
            builder.WriteLine($"namespace {ns}")
                   .WriteOpeningBracket();

            // Class description
            WriteQualifiers(builder, classItem.Qualifiers);

            var className = _regex.Replace(classItem.Name, "");
            // Class declaration
            builder.WriteLine($"public class {className}")
                   .WriteOpeningBracket();

            foreach (var property in classItem.Properties.Where(m => m.CimType != CimType.Reference))
            {
                // Property description
                WriteQualifiers(builder, property.Qualifiers);

                var type = property.Type;
                if (property.IsArray)
                {
                    type += "[]";
                }
                builder.WriteLine($"public {type} {property.Name} {{ get; set; }}");
            }

            // End class declaration
            builder.WriteClosingBracket();

            // End namespace declaration
            builder.WriteClosingBracket();

            return ($"{ns}.{classItem.Name}.g.cs", builder.ToString());
        }

        internal static void WriteQualifiers(SourceBuilder builder, Qualifiers qualifiers)
        {
            var lines = new List<string>();
            lines.AddRange(qualifiers.Descriptions);
            lines.Add(string.Empty);
            foreach (var (key, values) in qualifiers.Others)
            {
                var sb = new StringBuilder(256);
                sb.Append(key);
                sb.Append(": ");
                foreach (var (value, _, _, isLast) in values.IndexExt())
                {
                    sb.Append(value);
                    if (!isLast)
                    {
                        sb.Append(", ");
                    }
                }
                lines.Add(sb.ToString());
                lines.Add(string.Empty);
            }
            builder.WriteSummary(lines);
        }
    }
}
