using System;
using System.Collections.Generic;
using System.Linq;
using System.Management;
using System.Text.RegularExpressions;
using FclEx.Wmi.SourceGenerator.Extensions;
using FclEx.Wmi.SourceGenerator.Models;

namespace FclEx.Wmi.SourceGenerator.Sources
{
    public static class ClassItemSource
    {
        internal const string GeneratedFilesHeader = "// <auto-generated />";

        private static readonly Regex _regex = new(@"(?<=[^_])_+(?=[^_])", RegexOptions.Compiled);

        internal static (string FileName, string Code) Generate(string @namespace, ClassItem classItem)
        {
            var usings = new List<string> { "System" };

            using var builder = new SourceBuilder()
                                .WriteLine(GeneratedFilesHeader)
                                .WriteLine()
                                .WriteUsings(usings)
                                .WriteLine();

            var ns = @namespace.TrimStart("root\\", StringComparison.OrdinalIgnoreCase).Replace("\\", ".");

            // Namespace declaration
            builder.WriteLine($"namespace {ns}")
                   .WriteOpeningBracket();

            // Class description
            builder.WriteSummary(classItem.Description);

            var className = _regex.Replace(classItem.Name, "");
            // Class declaration
            builder.WriteLine($"public class {className}")
                   .WriteOpeningBracket();

            foreach (var property in classItem.Properties.Where(m => m.CimType != CimType.Reference))
            {
                // Property description
                builder.WriteSummary(property.Description);

                var type = property.Type;
                if (property.IsArray)
                {
                    type += "[]";
                }
                builder.WriteLine($"public {type} {property.Name};");
            }

            // End class declaration
            builder.WriteClosingBracket();

            // End namespace declaration
            builder.WriteClosingBracket();

            return ($"{ns}.{classItem.Name}.g.cs", builder.ToString());
        }
    }
}
