<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\nupkg\common.test.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx\FclEx.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
