<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\nupkg\common.test.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx\FclEx.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="16.10.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="test-data\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
