<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Http\FclEx.Http.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\SimpleCookies.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xRetry" Version="1.9.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" PrivateAssets="all" />
  </ItemGroup>

</Project>
