<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MimeTypeMap.Core" Version="1.0.0" />
    <PackageReference Include="HttpMultipartParser" Version="8.1.0" />
    <PackageReference Include="AngleSharp" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx\FclEx.csproj" />
  </ItemGroup>
  
</Project>
