<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx\FclEx.csproj" />
  </ItemGroup>
  
</Project>
