// Global using directives

global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.Specialized;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.IO.Compression;
global using System.Linq;
global using System.Net;
global using System.Net.Http;
global using System.Net.Mime;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using AngleSharp.Html.Dom;
global using AngleSharp.Html.Parser;
global using FclEx.Extensions;
global using FclEx.Helpers;
global using FclEx.Http;
global using FclEx.Utils;
global using FclEx.Web;
global using Microsoft.Collections.Extensions;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Http;
global using Microsoft.Extensions.Logging;
global using MimeTypes.Core;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using Polly;
global using Polly.Extensions.Http;
global using Polly.Timeout;
global using HttpClientResolver = System.Func<System.Net.Http.HttpClient>;
global using SleepDurationProvider = System.Func<int, System.TimeSpan>;