<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ServiceStack.OrmLite.Sqlite</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.116" />
    <ProjectReference Include="..\ServiceStack.OrmLite\ServiceStack.OrmLite.Custom.csproj" />
  </ItemGroup>

</Project>
