<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="8.0.10" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="YamlDotNet" Version="16.1.3" />
    <PackageReference Include="PolySharp" Version="1.14.1" /> <!--to support C# feature like required keyword in lower dotnet versions-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FclEx.SourceGenerator\FclEx.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Import Project="..\EmitGeneratedFiles.props" Condition="'$(Configuration)' == 'Debug' AND $(GITHUB_ACTION) == ''" />

  <ItemGroup Label="FilesToCopy">
    <Content Include="FclExUsing.cs" Pack="true" BuildAction="None" PackagePath="content/" />
    <Content Include="FclEx.targets" Pack="true" BuildAction="None" PackagePath="buildTransitive/" />
  </ItemGroup>

</Project>
