<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.AspNetCore\FclEx.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\FclEx.Http\FclEx.Http.csproj" />
    <ProjectReference Include="..\FclEx.Tests\FclEx.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\SimpleCookies.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
  </ItemGroup>

</Project>
