<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!--to support C# feature like required keyword in lower dotnet versions-->
    <PackageReference Include="PolySharp" Version="1.15.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Http\FclEx.Http.csproj" />
    <ProjectReference Include="..\FclEx.Core.Tests\FclEx.Core.Tests.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::VersionLessThan($(TargetFrameworkVersion), 5.0))">
    <Reference Include="System.Web" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(TargetFrameworkVersion), 8.0))">
    <ProjectReference Include="..\..\src\FclEx.AspNetCore\FclEx.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\SimpleCookies.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
