<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <!--to support C# feature like required keyword in lower dotnet versions-->
    <PackageReference Include="PolySharp" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Http\FclEx.Http.csproj" />
    <ProjectReference Include="..\..\src\FclEx.AspNetCore\FclEx.AspNetCore.csproj" />
    <ProjectReference Include="..\FclEx.Core.Tests\FclEx.Core.Tests.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.*" />
  </ItemGroup>
</Project>