// Global using directives

global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Diagnostics.Tracing;
global using System.Net;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.Text.Json.Serialization;
global using FclEx.AspNetCore;
global using FclEx.Extensions;
global using FclEx.Helpers;
global using FclEx.Http;
global using FclEx.Http.Tests.Models;
global using FclEx.Utils;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.RequestDecompression;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Http;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Polly.Timeout;
global using xRetry;
global using Xunit;
global using Xunit.Abstractions;
global using Xunit.Extensions.AssemblyFixture;
global using static FclEx.Http.Tests.HttpFixture;