<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Xunit.v3\FclEx.Xunit.v3.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!--xunit.v3 is required to discover tests when a test project is running using dotnet command.-->
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Meziantou.Xunit.v3.ParallelTestFramework" />
    <PackageReference Include="xRetry.v3" />
    <PackageReference Include="morelinq" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Xunit.v3.Priority" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Reference Include="System.IO.Compression" />
  </ItemGroup>
</Project>