<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Abp.RedisCache\FclEx.Abp.RedisCache.csproj" />
    <ProjectReference Include="..\FclEx.Abp.Tests\FclEx.Abp.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.github.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Unreachable.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
