using System;
using System.Collections.Generic;
using System.Linq;
using FclEx.Wmi.SourceGenerator.Models;
using Microsoft.CodeAnalysis;

namespace FclEx.Wmi.SourceGenerator.Sources
{
    public static class ClassItemSource
    {
        internal const string RootNamespace = "InterfaceBaseInvoke.Tests.Weaving";
        internal const string GeneratedFilesHeader = "// <auto-generated />";

        internal static (string FileName, string Code) Generate(ClassItem classItem)
        {
            var usings = new List<string> { "System" };

            using var builder = new SourceBuilder()
                                .WriteLine(GeneratedFilesHeader)
                                .WriteLine()
                                .WriteUsings(usings)
                                .WriteLine();

            // Namespace declaration
            builder.WriteLine($"namespace {RootNamespace}")
                   .WriteOpeningBracket();

            // Class declaration
            builder.WriteLine($"public class {classItem.Name}")
                   .WriteOpeningBracket();

            foreach (var property in classItem.Properties)
            {
                builder.WriteLine($"public {property.Type} {property.Name};");
            }

            // End class declaration
            builder.WriteClosingBracket();

            return ($"{classItem.Name}.g.cs", builder.ToString());
        }
    }
}
