# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOTNET_NOLOGO: 1
  MYGET_APIKEY: ${{ secrets.MYGET_APIKEY }}
  SOLUTION: src/FclEx.All.sln

jobs:    
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: heidiks/rabbitmq-delayed-message-exchange:3.8.27-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.0.x
            7.0.x

      - name: Test Release
        shell: pwsh
        run: |
          ./build/test_all.ps1 Release

      - name: NuGet Publish
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: pwsh
        run: |
          ./build/pack.ps1 no-restore

  build-windows:
    needs: build
    runs-on: windows-2019    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.0.x
            7.0.x 

      - name: Test Release
        shell: pwsh        
        run: |
          ./build/test_all.ps1 Release

      - name: NuGet Publish
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: pwsh
        run: |
          ./build/pack.ps1 no-restore

      - name: Set variables
        run: |
          $ver = Get-Content -Path ./build/pkg.version
          echo "VERSION=$ver" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo $ver
          
      - name: Create Tag
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          skipIfReleaseExists: true   