<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="MySql.Data" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Condition="$(SupportOracle)" />
    <ProjectReference Include="../../src/FclEx.Dapper/FclEx.Dapper.csproj" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Reference Include="System.ComponentModel.DataAnnotations" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Xunit.v3\FclEx.Xunit.v3.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Schemas/Sqlite.sql" LogicalName="FclEx.DatabaseTesting.Sqlite.sql" />
  </ItemGroup>
</Project>
