<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType Condition="$([MSBuild]::VersionLessThan($(TargetFrameworkVersion), 5.0))">Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Meziantou.Xunit.ParallelTestFramework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FclEx.Xunit\FclEx.Xunit.csproj" />
    <ProjectReference Include="..\..\src\FclEx.Xunit.SourceGenerator\FclEx.Xunit.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <Import Project="..\..\src\EmitGeneratedFiles.props" Condition=" '$(Configuration)' == 'Debug' AND $(GITHUB_ACTION) == '' AND '$(OS)' == 'Windows_NT' " />
</Project>