// Licensed under the MIT License.  See License.txt in the project root for license information.
// <autogenerated/> Autogenerated using EmojiSiteProcessor. Do not edit by hand.
// https://github.com/RamjotSingh/EmojiNet/blob/main/EmojiNet/RamjotSingh.EmojiNet/UnicodeScalarHelper.cs
namespace FclEx.Helpers;

/// <summary>
/// Helpers for Unicode scalars.
/// </summary>
// ReSharper disable once PartialTypeWithSinglePart
public static partial class UnicodeScalarHelper
{
    /// <summary>
    /// Detects if the passed Unicode scalar corresponds to a well known emoji.
    /// </summary>
    /// <param name="unicodeScalar">Unicode scalar to check.</param>
    /// <returns>True if the passed Unicode scalar is an emoji, false otherwise.</returns>
    public static partial bool IsEmoji(int unicodeScalar);
}