<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Convenience extensions for service registration, replacement, removal, decoration, scopes, and provider lookup.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FclEx.Core\FclEx.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FclEx.SourceGenerator\FclEx.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <Import Project="..\EmitGeneratedFiles.props" Condition=" '$(Configuration)' == 'Debug' AND $(GITHUB_ACTION) == '' AND '$(OS)' == 'Windows_NT' " />
</Project>
